export const GET_RANDOM_MOVIE = "GET_RANDOM_MOVIE";
 export const SEND_MOVIE_GENRE_CODE = "SEND_MOVIE_GENRE_CODE";
 export const SEND_MOVIE_GENRE_NAME = "SEND_MOVIE_GENRE_NAME";
 export const CHANGE_TO_DECADE_PAGE = "CHANGE_TO_DECADE_PAGE";
 export const SEND_MOVIE_DECADE_OBJECT = "SEND_MOVIE_DECADE_OBJECT";
 export const SEND_MOVIE_DECADE_STRING = "SEND_MOVIE_DECADE_STRING";

 export const ADD_ERROR = 'ADD_ERROR';
 export const REMOVE_ERROR = 'ERROR_REMOVE';

 export const SET_CURRENT_USER = 'SET_CURRENT_USER';

 export const GENRE_BTN_CLICKED = 'GENRE_BTN_CLICKED';

export const DECADE_BTN_CLICKED = 'DECADE_BTN_CLICKED';

export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const SET_CURRENT_WATCHED_MOVIE = 'SET_CURRENT_WATCHED_MOVIE';
export const SET_ALL_WATCHED_MOVIES = 'SET_ALL_WATCHED_MOVIES';




 



