export const GET_RANDOM_MOVIE = "GET_RANDOM_MOVIE";
 export const SEND_MOVIE_GENRE_CODE = "SEND_MOVIE_GENRE_CODE";
 export const SEND_MOVIE_GENRE_NAME = "SEND_MOVIE_GENRE_NAME";
 export const CHANGE_TO_DECADE_PAGE = "CHANGE_TO_DECADE_PAGE";
 export const SEND_MOVIE_DECADE_OBJECT = "SEND_MOVIE_DECADE_OBJECT";
 export const SEND_MOVIE_DECADE_STRING = "SEND_MOVIE_DECADE_STRING";

 export const ADD_ERROR = 'ADD_ERROR';
 export const REMOVE_ERROR = 'ERROR_REMOVE';

 export const SET_CURRENT_USER = 'SET_CURRENT_USER';


 



